# account 是你的登陆账号在offline时不用填写  
# login 是你的登陆模式，可以在 microsoft，mojang，offline中选择
# 使用微软登陆时，这里只需填写login字段，其他可以忽略或删除
# name 在离线登陆（offline）时必填,在其他登陆模式时会被忽略
# passwd 是你的登陆密码在offline时不用填写  
[profile]
  account = "example@example.com"
  login = "microsoft"
  name = "yourid"
  passwd = "password"

# ip 请填写你的服务器ip
# port 一般情况都是25565，少数服务器会使用其他端口
# timeout 是钓鱼等待时间，超过这个时间即使没有钓到鱼也会收杆，一般而言tps20的服务器timeout应该设置为45
[setting]
  ip = "play.miaoscraft.cn"
  port = 25565
  timeout = 45
